name: Publish Docker Image

# Ejecutar el workflow solo cuando se crea un tag
on:
  push:
    tags:
      - 'v*'  # Esto se activará para tags que comiencen con "v", como "v1.0", "v2.0", etc.

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Comprobar el repositorio
      - name: Check out the repository
        uses: actions/checkout@v2

      # Paso 2: Log in a DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # Paso 3: Configurar el tag de la imagen
      - name: Set up Docker image tag
        id: image_tag
        run: echo "IMAGE_TAG=${GITHUB_REF##*/}" >> $GITHUB_ENV

      # Paso 4: Construir la imagen de Docker
      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/my-image:${{ env.IMAGE_TAG }} .

      # Paso 5: Subir la imagen a DockerHub
      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/my-image:${{ env.IMAGE_TAG }}
